In [1]:
import numpy as np

# **Testing Performance**

In [ ]:
n=100000000

In [ ]:
%%time
list1 = list(range(n))
for i in range(n):
  list1[i] = list1[i] * list1[i]

CPU times: user 22.8 s, sys: 2.18 s, total: 25 s
Wall time: 27.6 s


In [ ]:
%%time
list1 = list(range(n))
list1 = map(lambda x : x * x,list1)

CPU times: user 1.32 s, sys: 2.11 s, total: 3.44 s
Wall time: 3.42 s


In [ ]:
%%time
list1 = list(range(n))
list1 = [i * i for i in list1]

CPU times: user 15.1 s, sys: 7.97 s, total: 23.1 s
Wall time: 23.3 s


In [ ]:
%%time
list1 = np.arange(n)
list1 = list1 * list1

CPU times: user 1.99 s, sys: 935 ms, total: 2.92 s
Wall time: 2.73 s


In [ ]:
%%time
list1 = list(range(n))
list1 = map(lambda x : x + x,list1)

CPU times: user 1.14 s, sys: 1.75 s, total: 2.89 s
Wall time: 2.88 s


In [ ]:
%%time
list1 = np.arange(n)
listsum = np.sum(list1)

CPU times: user 152 ms, sys: 160 ms, total: 312 ms
Wall time: 314 ms


In [ ]:
%%time
list1 = list(range(n))
listsum = sum(list1)

CPU times: user 3.88 s, sys: 2.37 s, total: 6.25 s
Wall time: 6.28 s


In [ ]:
%%time
listsum = 0
list1 = np.arange(n)
for i in list1:
  listsum += i

CPU times: user 17.3 s, sys: 753 ms, total: 18.1 s
Wall time: 18.2 s


# **NumPy Arrays**

In [ ]:
arr = np.array([[2,34,5,6],[4,52,74,7]])

In [ ]:
#arr = np.arange(5)
print(arr, type(arr))
print(arr.dtype, arr.ndim, arr.shape, arr.size, arr.itemsize)

[[ 2 34  5  6]
 [ 4 52 74  7]] <class 'numpy.ndarray'>
int64 2 (2, 4) 8 8


In [ ]:
arr = np.array([[[2,4,6,7,4],[4,2,5,7,6],[2,2,5,5,6]],[[5,2,3,4,4],[3,4,5,6,6],[4,6,3,2,5]]])

In [ ]:
257*np.ones((2,4,3))

array([[[257., 257., 257.],
        [257., 257., 257.],
        [257., 257., 257.],
        [257., 257., 257.]],

       [[257., 257., 257.],
        [257., 257., 257.],
        [257., 257., 257.],
        [257., 257., 257.]]])

In [ ]:
np.zeros((2,1,4))

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [ ]:
np.random.randn(3,4)

array([[ 1.02332728, -0.68092443,  1.11262895,  1.90425042],
       [-1.33219728, -1.2629679 , -0.44885633,  0.66841307],
       [-1.48883322,  0.17330933, -0.92424199,  0.24675699]])

In [ ]:
np.random.randn(2,3)

array([[ 0.74458025, -1.51177807,  0.8986887 ],
       [-0.46322691, -0.86747716,  0.21136052]])

In [ ]:
np.random.rand(10,1)

array([[0.68409735],
       [0.20892315],
       [0.22567072],
       [0.6786635 ],
       [0.06109755],
       [0.37282762],
       [0.80072505],
       [0.16303888],
       [0.05282273],
       [0.79461821]])

In [ ]:
np.random.randint(1,100,(2,3))

array([[81, 76, 61],
       [23, 27, 14]])

In [ ]:
np.arange(1,100,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [ ]:
np.linspace(1,100,6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [ ]:
np.array(['1.3','4.5','5.6'])

array(['1.3', '4.5', '5.6'], dtype='<U3')

In [ ]:
str_arr = np.array(['1.3','4.5','5.6'])
arr = np.array(str_arr, dtype = 'float')
print(arr)

[1.3 4.5 5.6]


# **Indexing**

In [ ]:
arr3d = np.array([[[2,4,6,7,4],[4,2,5,7,6],[2,2,5,5,6]],[[5,2,3,4,4],[3,4,5,6,6],[4,6,3,2,5]]])

In [ ]:
arr3d[1,0,2]

3

In [ ]:
arr3d[0,:,0:2]

array([[2, 4],
       [4, 2],
       [2, 2]])

In [ ]:
arr3d % 2 == 0

array([[[ True,  True,  True, False,  True],
        [ True,  True, False, False,  True],
        [ True,  True, False, False,  True]],

       [[False,  True, False,  True,  True],
        [False,  True, False,  True,  True],
        [ True,  True, False,  True, False]]])

In [ ]:
arr3d[(arr3d % 2 == 0) & (arr3d > 3)]

array([4, 6, 4, 4, 6, 6, 4, 4, 4, 6, 6, 4, 6])

In [ ]:
arrslice = arr3d[0,0:2,1:4]

In [ ]:
arrslice.shape

(2, 3)

In [ ]:
arrslice.ndim

2

In [ ]:
arrslice[0,0] = 65
print(arr3d)

[[[ 2 65  6  7  4]
  [ 4  2  5  7  6]
  [ 2  2  5  5  6]]

 [[ 5  2  3  4  4]
  [ 3  4  5  6  6]
  [ 4  6  3  2  5]]]


In [ ]:
arr = np.random.randint(1,100,6)
indices = np.array([1,3,5])
arr[indices]

array([28, 92, 40])

In [ ]:
arr

array([91, 28, 60, 92, 32, 40])

# **Numpy Operations**



In [ ]:
arr1 = np.random.randn(3,4)
arr2 = np.random.randn(3,4)

In [ ]:
arr1

array([[ 2.02033304,  0.78460686,  0.25108598,  0.22320318],
       [-0.22048669, -0.31692413, -0.34084444,  1.44666757],
       [ 1.44025673, -0.92425056, -1.49365372,  0.16566816]])

In [ ]:
arr1 + arr2

array([[ 1.47586151, -0.8879321 ,  0.03406052,  1.56252463],
       [-1.28866229, -0.62313403,  0.08688311,  1.39248233],
       [ 2.32223645, -1.78511366, -1.18119517,  0.50384731]])

In [ ]:
arr1 - arr2

array([[ 2.56480457,  2.45714582,  0.46811144, -1.11611828],
       [ 0.84768892, -0.01071422, -0.76857199,  1.50085281],
       [ 0.55827702, -0.06338745, -1.80611227, -0.172511  ]])

In [ ]:
arr1 * arr2

array([[-1.10001382, -1.31228555, -0.05449205,  0.2989408 ],
       [ 0.2355185 ,  0.09704531, -0.14578856, -0.07838803],
       [ 1.27027722,  0.7956532 , -0.46670488,  0.05602552]])

In [ ]:
np.exp(arr1)

array([[7.54083595, 2.19154519, 1.2854206 , 1.25007453],
       [0.80212832, 0.72838602, 0.71116953, 4.24893162],
       [4.22177955, 0.39682871, 0.22455071, 1.1801814 ]])

In [ ]:
np.log(np.exp(arr1))

array([[ 2.02033304,  0.78460686,  0.25108598,  0.22320318],
       [-0.22048669, -0.31692413, -0.34084444,  1.44666757],
       [ 1.44025673, -0.92425056, -1.49365372,  0.16566816]])

In [ ]:
np.sin(arr1)

array([[ 0.90064852,  0.70654703,  0.24845603,  0.22135447],
       [-0.21870455, -0.31164535, -0.33428307,  0.99230591],
       [ 0.9914918 , -0.7981695 , -0.99702598,  0.16491138]])

In [ ]:
np.sqrt(np.exp(arr1))

array([[2.74605826, 1.48038684, 1.13376391, 1.11806732],
       [0.89561617, 0.85345534, 0.84330868, 2.06129368],
       [2.05469695, 0.62994342, 0.47386782, 1.08636154]])

In [ ]:
arr3 = np.zeros((3,4))

In [ ]:
arr_inv = 1 / arr3

<ipython-input-45-276885efaf0a>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_inv = 1 / arr3


In [ ]:
arr_inv

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [ ]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# **Question**

Find the area of the region which enclosed within a unit square excluding the area of a unit quarter circle. Do the same for higher dimensions. Draw some inferences on the results.

In [ ]:
ndim = 2

In [ ]:
npoints = 1000000

In [ ]:
points = np.random.rand(npoints,ndim)

In [ ]:
dfo = np.zeros((npoints,1))
c = 0

In [ ]:
%%time
for i in range(npoints):
  for j in range(ndim):
    dfo[i] +=  points[i,j] ** 2
  dfo[i] = np.sqrt(dfo[i])
  if(dfo[i] > 1):
    c += 1

CPU times: user 15.5 s, sys: 865 ms, total: 16.4 s
Wall time: 15.9 s


In [ ]:
print("fraction = ",c/npoints)

fraction =  0.214596


In [ ]:
%%time
print("fraction = ",np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1)/npoints)

fraction =  0.214596
CPU times: user 31.3 ms, sys: 8.51 ms, total: 39.8 ms
Wall time: 43.1 ms


In [ ]:
def area_ndim(npoints,ndim):
  points = np.random.rand(npoints,ndim)
  print("fraction = ",np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1)/npoints)

In [ ]:
for i in range(2,12):
  area_ndim(npoints,i)

fraction =  0.214903
fraction =  0.47537
fraction =  0.691754
fraction =  0.83559
fraction =  0.919641
fraction =  0.963008
fraction =  0.983944
fraction =  0.993628
fraction =  0.9975
fraction =  0.99907


# **Broadcasting**

In [ ]:
arr = np.arange(6)

In [ ]:
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr1 = arr.reshape(2,3)

In [ ]:
arr2 = np.arange(6).reshape(3,2)

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr4 = arr[0:3]
arr4.reshape(1,3)

array([[0, 1, 2]])

In [ ]:
arr4 + arr1

array([[0, 2, 4],
       [3, 5, 7]])

In [ ]:
arr1 = np.arange(24).reshape(2,3,4)

In [ ]:
arr2 = np.arange(4).reshape(1,4)

In [ ]:
arr1 + arr2

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[12, 14, 16, 18],
        [16, 18, 20, 22],
        [20, 22, 24, 26]]])

In [ ]:
arr1 = np.arange(4).reshape(4,1)
arr2 = np.arange(5).reshape(5,1)
arr1 + arr2.T

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [ ]:
arr1 = np.random.rand(3,4)

In [ ]:
arr1

array([[4.86915380e-01, 6.86802223e-01, 6.28913821e-01, 3.96414531e-01],
       [8.23794281e-01, 7.24520277e-04, 1.45785350e-01, 4.59367932e-01],
       [1.73344685e-01, 5.43272528e-01, 9.09280798e-01, 2.66848227e-03]])

In [ ]:
arr1.T

array([[4.86915380e-01, 8.23794281e-01, 1.73344685e-01],
       [6.86802223e-01, 7.24520277e-04, 5.43272528e-01],
       [6.28913821e-01, 1.45785350e-01, 9.09280798e-01],
       [3.96414531e-01, 4.59367932e-01, 2.66848227e-03]])

# **File Handling**

In [ ]:
planets_small = np.loadtxt('planets_small.txt', skiprows = 1, usecols = (1,2,3,4,5,6,7,8,9))

In [ ]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets_small.shape

(3, 9)

In [ ]:
planets = np.genfromtxt('planets.txt', skip_header = 1, usecols = (1,2,3,4,5,6,7,8,9))

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
planets_new = np.nan_to_num(planets,nan = -1)

In [ ]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
np.savetxt('planets_new.txt',planets_new, delimiter = ',')

In [ ]:
np.save('planets_new',planets_new)

In [ ]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Jun  4 05:50 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jun  4 05:28 planets_new.txt
-rw-r--r-- 1 root root  257 Jun  4 05:14 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jun  4 05:14 planets.txt
drwxr-xr-x 1 root root 4.0K Jun  1 22:51 sample_data


In [ ]:
arr1 = np.random.rand(1000,10)
arr2 = np.random.rand(2000,5)
arr3 = np.random.rand(20,10000)

In [ ]:
np.savez('many_arr',arr1,arr2,arr3)

In [ ]:
many_arr = np.load('many_arr.npz')

In [ ]:
many_arr.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
many_arr['arr_0'].shape

(1000, 10)

In [ ]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.6M Jun  4 06:04 many_arr_com.npz
-rw-r--r-- 1 root root 1.7M Jun  4 06:03 many_arr.npz
-rw-r--r-- 1 root root 1.6K Jun  4 05:50 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jun  4 05:28 planets_new.txt
-rw-r--r-- 1 root root  257 Jun  4 05:14 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jun  4 05:14 planets.txt
drwxr-xr-x 1 root root 4.0K Jun  1 22:51 sample_data


In [ ]:
np.savez_compressed('many_arr_com',arr1,arr2,arr3)

In [ ]:
arr1 = np.zeros((10000,10000))

In [ ]:
np.savez('zeros',arr1)

In [ ]:
np.savez_compressed('zeros_1',arr1)

In [ ]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.6M Jun  4 06:04 many_arr_com.npz
-rw-r--r-- 1 root root 1.7M Jun  4 06:03 many_arr.npz
-rw-r--r-- 1 root root 1.6K Jun  4 05:50 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jun  4 05:28 planets_new.txt
-rw-r--r-- 1 root root  257 Jun  4 05:14 planets_small.txt
-rw-r--r-- 1 root root 1.5K Jun  4 05:14 planets.txt
drwxr-xr-x 1 root root 4.0K Jun  1 22:51 sample_data
-rw-r--r-- 1 root root 760K Jun  4 06:09 zeros_1.npz
-rw-r--r-- 1 root root 763M Jun  4 06:09 zeros.npz


# **Stats with NumPy**

In [ ]:
arr1 = np.random.rand(1000000,)

In [ ]:
np.amin(arr1)

5.206540574231866e-07

In [ ]:
np.amax(arr1)

0.9999998237263988

In [ ]:
np.mean(arr1)

0.5003978229649292

In [ ]:
np.var(arr1)

0.08340566463184759

In [ ]:
np.std(arr1)

0.28880038890529147

In [ ]:
np.median(arr1)

0.5004484051331555

In [ ]:
np.percentile(arr1,50)

0.5004484051331555

In [ ]:
np.percentile(arr1,30)

0.3001435836419799

In [ ]:
%%time
iqr = np.percentile(arr1,75) - np.percentile(arr1,25)

CPU times: user 34.1 ms, sys: 0 ns, total: 34.1 ms
Wall time: 38.1 ms


In [ ]:
iqr

0.5008761787174134

In [ ]:
%%time
iqr_arr = np.percentile(arr1,[25,75])
iqr = iqr_arr[1] - iqr_arr[0]

CPU times: user 26.1 ms, sys: 0 ns, total: 26.1 ms
Wall time: 34 ms


In [ ]:
iqr

0.5008761787174134

In [ ]:
(arr1 - np.mean(arr1))/np.std(arr1)

array([ 1.02348243, -1.6168381 ,  0.62455246, ..., -0.80656488,
        1.10425683,  0.72060293])

In [ ]:
np.histogram(arr1)

(array([ 99828,  99782, 100255,  99743,  99941, 100108,  99749,  99650,
        100595, 100349]),
 array([5.20654057e-07, 1.00000451e-01, 2.00000381e-01, 3.00000312e-01,
        4.00000242e-01, 5.00000172e-01, 6.00000102e-01, 7.00000033e-01,
        7.99999963e-01, 8.99999893e-01, 9.99999824e-01]))

In [ ]:
np.histogram(arr1,bins=5)

(array([199610, 199998, 200049, 199399, 200944]),
 array([5.20654057e-07, 2.00000381e-01, 4.00000242e-01, 6.00000102e-01,
        7.99999963e-01, 9.99999824e-01]))

In [ ]:
np.histogram(arr1,[0,0.25,0.5,0.75,1])

(array([249948, 249600, 249622, 250830]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0,0.25,0.5,0.75,1]

In [ ]:
np.digitize(arr1,bins) # default as left inclusion

array([4, 1, 3, ..., 2, 4, 3])

In [ ]:
np.digitize(arr1,bins,right = True) # for not incuding left

array([4, 1, 3, ..., 2, 4, 3])

In [ ]:
arr1 = np.random.randint(50,75,100)
arr2 = np.random.randint(150,165,100)
arr3 = np.random.randint(17,22,100)

In [ ]:
np.concatenate((arr1,arr2,arr3))

array([ 52,  55,  52,  69,  66,  73,  67,  64,  52,  71,  67,  64,  66,
        53,  65,  68,  52,  56,  63,  63,  72,  69,  60,  51,  64,  62,
        74,  56,  67,  53,  70,  72,  52,  51,  74,  67,  74,  51,  67,
        66,  66,  50,  68,  51,  67,  70,  64,  52,  64,  64,  59,  67,
        63,  60,  70,  54,  69,  59,  55,  50,  56,  60,  64,  59,  74,
        63,  64,  57,  65,  51,  67,  71,  50,  60,  52,  53,  63,  66,
        55,  50,  67,  53,  70,  64,  73,  73,  51,  69,  53,  56,  67,
        64,  50,  74,  70,  70,  64,  55,  69,  53, 153, 162, 160, 152,
       152, 157, 152, 156, 151, 162, 158, 163, 152, 161, 161, 160, 156,
       151, 151, 152, 159, 163, 155, 155, 155, 155, 150, 156, 159, 162,
       155, 154, 162, 150, 156, 153, 159, 157, 161, 154, 155, 160, 151,
       159, 155, 154, 156, 161, 158, 164, 151, 154, 152, 156, 150, 152,
       164, 162, 157, 152, 158, 161, 161, 163, 161, 162, 156, 161, 163,
       159, 151, 150, 162, 159, 159, 151, 161, 154, 162, 156, 16

In [ ]:
np.concatenate((arr1,arr2,arr3)).shape

(300,)

In [ ]:
arr2d = np.vstack((arr1,arr2,arr3))

In [ ]:
np.amin(arr2d)

17

In [ ]:
np.amin(arr2d, axis = 1)

array([ 50, 150,  17])

In [ ]:
np.amax(arr2d, axis = 1)

array([ 74, 164,  21])

In [ ]:
np.mean(arr2d, axis = 1)

array([ 61.97, 156.53,  19.16])

# **Case Study & Problems**

In [ ]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216





1.   Find mean, median, IQR for Sachin, Rahul, and India
2.   Find the histogram of Sachin's scores with 10 bins
3.   Find mean of Sachin's scores grouped by 25 matches
4.   Find mean of Sachin's scores where he has score a century
5.   Find mean of Sachin's scores when Rahul has scored less than 10
6.   Find mean for Sachin's scores based on which quartile India's score falls in
7.   For every match find out who has scored more - Sachin or Rahul
8.   How many more runs does Sachin score on average after having sored x runs
9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs...





## Problem 1

In [5]:
cric_data = np.loadtxt("cric_data.tsv", skiprows= 1)

In [6]:
cric_data.shape

(225, 4)

In [7]:
cric_data = cric_data[:,[1,2,3]]

In [8]:
cric_data.shape

(225, 3)

In [9]:
sachin = cric_data[:,0]

In [10]:
rahul = cric_data[:,1]

In [11]:
india = cric_data[:,2]

In [12]:
def stats(col):
  print("Mean",np.mean(col))
  print("Median",np.median(col))
  print("IQR", np.percentile(col,75) - np.percentile(col,25))

In [13]:
stats(sachin)

Mean 39.87555555555556
Median 27.0
IQR 57.0


In [14]:
stats(rahul)

Mean 32.062222222222225
Median 22.0
IQR 46.0


In [15]:
stats(india)

Mean 220.79555555555555
Median 216.0
IQR 98.0


In [16]:
np.mean(cric_data, axis = 0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [17]:
np.median(cric_data, axis = 0)

array([ 27.,  22., 216.])

In [18]:
np.percentile(cric_data, 75, axis = 0) - np.percentile(cric_data, 25,axis = 0)

array([57., 46., 98.])

## Problem 2

In [19]:
np.histogram(sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

## Problem 3

In [20]:
sachin.shape

(225,)

In [21]:
sachin_by_25s = sachin.reshape(9,25)

In [22]:
np.mean(sachin_by_25s, axis = 1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

## Problem 4

In [23]:
np.mean(sachin[sachin>=100])

125.0

## Problem 5

In [24]:
np.mean(sachin[rahul<=10])

40.2112676056338

##Problem 6

In [25]:
qrs = np.percentile(india,[25,50,75,100])

In [26]:
india < 175

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False,  True, False, False,  True,
       False, False,  True, False, False, False, False,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
        True, False,

In [27]:
india.shape

(225,)

In [28]:
qrs.shape

(4,)

In [31]:
qrs = qrs.reshape(4,1)

In [34]:
indices = india < qrs

In [36]:
indices.shape

(4, 225)

In [37]:
sachin[indices[1,:]]

array([ 11.,  18.,  14.,   4.,   0.,  21.,  62.,   2.,  46.,  65.,   0.,
        39.,  48.,   3.,  11.,   5.,  65.,  27.,   7.,   2.,  28.,   6.,
         7.,   3.,   2.,   4., 100.,  15.,  32.,  40.,   0.,   5.,   8.,
         5.,   0.,  30.,  37.,  89.,   0.,  52.,  93.,  45.,   0.,   1.,
         0.,   3.,   0.,  81.,  78.,   6.,  28.,  13.,  93.,   2.,  36.,
         2.,  12.,  19.,  34.,   2.,  82.,   0.,   6.,   8.,  23.,  35.,
        74., 117.,  49.,  64.,   5.,  17.,   0.,  44.,  68.,   3.,  47.,
        17.,  35.,  88., 127.,   0.,  45.,  33., 110.,   7.,  25.,   9.,
         2.,  11.,  17.,   1.,  45.,   9.,  67.,  10.,  55.,   0.,   1.,
       101.,  23.,   1.,  41.,   1.,  28.,   2.,  22.,  25.,   0.,  27.,
        40.])

In [38]:
for i in range(4):
  print(i, np.mean(sachin[indices[i]]))

0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


## Problem 7

In [39]:
snr = cric_data[:,0:2]

In [41]:
rahul_higher = np.argmax(snr, axis = 1)  # gives the position of max number, 0 corresponds to sachin and 1 corresponds to rahul

In [42]:
np.sum(rahul_higher) / 225

0.4711111111111111

In [43]:
np.where(rahul_higher == 0, 'Sachin', 'Rahul')

array(['Sachin', 'Rahul', 'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin',
       'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin',
       'Rahul', 'Rahul', 'Sachin', 'Rahul', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Rahul', 'Rahul', 'Sachin', 'Rahul',
       'Rahul', 'Sachin', 'Rahul', 'Rahul', 'Rahul', 'Rahul', 'Rahul',
       'Rahul', 'Sachin', 'Sachin', 'Sachin', 'Rahul', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Sachin', 'Sachin'

## Problem 8

In [50]:
x_arr = np.arange(0, 101, 5)

In [52]:
x_arr = x_arr.reshape(x_arr.shape[0], 1)

In [47]:
indices = sachin >= x_arr.reshape(x_arr.shape[0], 1)

In [48]:
indices.shape

(21, 225)

In [49]:
sachin[indices[1,:]]

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         7.,  37.,  14.,  21.,  62., 138.,  38.,  46.,  65.,  39.,  48.,
       141.,  62.,  12.,  41.,  11., 186.,  11.,  27.,  27.,  51.,  18.,
        32., 146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,  28.,
         6., 123., 120.,   7.,  81.,  54., 122.,  14., 100.,  15.,  57.,
        99.,  37.,  38.,  32.,  21.,  32.,  40.,   5.,   8.,   5.,  50.,
        30.,  37.,  89.,  98.,  83.,  93.,  52., 152.,   8.,  93.,  45.,
        26.,  16.,  47.,  89.,  53.,  16.,  81.,  14.,  78.,   6., 105.,
       122.,   9.,   8.,  28.,  35.,  69.,  13.,  97.,  93.,  36.,  39.,
        29.,  12.,  19.,  34., 100.,  44.,  82.,  79.,   6.,   9.,   8.,
        23.,  93.,  35.,  63.,  74.,   8., 117.,  39.,  49.,  64.,  43.,
        72.,   5.,  17.,  65.,  20., 141.,  28.,  44.,  27.,  60.,  68.,
       139.,  31.,  44.,  47.,   6.,  17.,  35.,  88., 114.,   7., 127.,
        45.,  33., 110., 146.,   7.,  25.,   9.,  1

In [53]:
for i in range(x_arr.shape[0]):
  print(x_arr[i, 0],
        np.mean(sachin[indices[i, : ]]) - x_arr[i,0])

0 39.87555555555556
5 45.61363636363637
10 47.48026315789474
15 47.45255474452555
20 46.824
25 44.10084033613445
30 45.13461538461539
35 43.24742268041237
40 44.05882352941177
45 43.41558441558442
50 43.98529411764706
55 42.317460317460316
60 38.67213114754098
65 37.654545454545456
70 37.08163265306122
75 34.347826086956516
80 30.75
85 28.650000000000006
90 27.400000000000006
95 26.433333333333337
100 25.0


## Problem 9

In [54]:
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [56]:
s_cum = np.cumsum(sachin)

In [57]:
np.histogram( s_cum, bins = np.arange(0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))

In [58]:
a = np.array([3,6,9,12,15])
b = np.array([2,4,6,8,12])
c = np.where(a == b)
print(c[0])

[]
